# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ujjwalkpandey/flyrank-internship/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

Lane 4 — CTR / Engagement Opportunity Scoring. I want to investigate which visible pages appear to under-capture clicks or engagement relative to their search visibility, so that a reviewer can prioritize which pages deserve metadata, content, or monitoring review. I chose this lane because the starter work already exposes impressions, CTR, average position, and engagement signals, and my Week 1 exploration showed that position and CTR are worth examining together rather than treating low CTR as a problem by itself.

In [5]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## 2. The question: decision, action, cost of a wrong call

Decision: Which visible pages should be prioritized for CTR or engagement review?
Action: A content/search reviewer would inspect the highest-priority pages and decide whether to review the title/meta/snippet, intent match, on-page engagement, or simply monitor the page.
Cost of a wrong call: A false positive wastes limited review time on a page that does not need intervention. A false negative is potentially more costly because a genuinely underperforming page may be missed. Low-volume pages are especially risky because apparent CTR or engagement problems can be noise.

In [6]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## 3. Quick look at the data (2-3 real numbers)

The starter dataset contains 30,000 rows. The median page has 731 90-day impressions, a 0.07 median CTR, and a 10.8 median average position. These numbers make the CTR/engagement lane worth investigating because the dataset contains substantial search exposure and directly measured click and position signals. However, the median values alone do not show that a page has a CTR problem; CTR needs to be interpreted alongside position and sufficient impression volume.

In [7]:
import pandas as pd

url = "https://raw.githubusercontent.com/ujjwalkpandey/flyrank-internship/main/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(url)

print("Rows:", len(df))
print("Median impressions_90d:", df["impressions_90d"].median())
print("Median CTR:", df["ctr"].median())
print("Median average position:", df["avg_position"].median())

Rows: 30000
Median impressions_90d: 731.0
Median CTR: 0.07
Median average position: 10.8


## 4. Careful words: what I can and can't claim

What I can claim: I can investigate whether observable search and engagement signals are associated with differences in CTR or engagement, and I can build a ranking that identifies pages that deserve human review. I can compare pages within appropriate position or volume groups and report directional relationships supported by the data.

What I cannot claim: I cannot claim that a low CTR proves a title or meta description is bad, that a particular signal causes higher rankings, or that changing a page will definitely improve performance. The data is observational, so an association is not proof of causation. I also need to control for low-volume noise and position differences before treating a page as an opportunity.

Validation principle: Any eventual scoring or model should be checked against an appropriate validation design and should not use future information as a feature.

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## Self-check

Self-check

Lane selected: Lane 4 — CTR / Engagement Opportunity Scoring.
Decision identified: which visible pages deserve CTR or engagement review first.
Action identified: a reviewer inspects the highest-priority pages and chooses review, improvement, or monitoring.
Cost of a wrong call identified: wasted review capacity for false positives and missed opportunities for false negatives.
Real starter-data numbers included: 30,000 rows, median 731 impressions, median CTR 0.07, median position 10.8.
Observable signals are being used rather than FlyRank's product decision outputs.
Causal claims are explicitly avoided.
Low-volume noise and position differences are recognized as risks.
The lane is provisional and can be changed later if the evidence points elsewhere.